#!/usr/bin/python2.7 -tt
from socket import*
import sys


bytes_rec = 100
requests_cnt = 0

def read_request(sock) :
    received_str = ''

    while True :
        received_str += sock.recv(bytes_rec)
        if received_str.find('\r\n\r\n') >= 0 :
            break

            if received_str.find('/counter') < 20 and received_str.find(' /counter ') > 0 :
                return True

                return False

                sock = socket()
                sock.connect('localhost', int(sys.argv[1]))

                end_str = '\r\n\r\n'
                ans_str = 'HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: '

                while True:
if read_request(sock) == True :
    requests_cnt += 1
    response = ans_str + str(len(str(requests_cnt))) + end_str + str(requestsCount) + end_str
    sock.send(response)

else:
sock.send('HTTP/1.1 404 Not Found\r\nContent-type: text/html\r\nContent-length: 113\r\n\r\n<html><head><title>Not Found</title></head><body>Sorry, the object you requested was not found.</body></html>\r\n\r\n')


