#!/usr/bin/python2.7 -tt
from socket import *
import sys

bytes_to_read = 120

def get_request(sock):
    msg_from_sock = ''

    while True:
        msg_from_sock += sock.recv(bytes_to_read)
        if msg_from_sock.find('\r\n\r\n') >= 0:
            break

    if msg_from_sock.find('/counter') < 25 and msg_from_sock.find(' /counter ') > 2:
        return 1
        
    return 0


sock = socket()
sock.connect(('localhost', int(sys.argv[1])))

req_counter = 0

while True:
    if get_request(sock) == 1: 
        req_counter += 1
        response = 'HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: '
        response = response + str(len(str(req_counter))) + '\r\n\r\n' + str(req_counter) +  '\r\n\r\n' 
        sock.send(response)
        
    else: 
        sock.send('HTTP/1.1 404 Not Found\r\nContent-type: text/html\r\nContent-length: 113\r\n\r\n<html><head><title>Not Found</title></head><body>Sorry, the object you requested was not found.</body></html>\r\n\r\n')
       

